---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgCLVBL4gPJ/huPgtWZw8QHyGfmaF73DdZIrabmbbmf/sZaHVcX9Lk71B3xMtI1eNcaXBJNuenDiQX5edL05PA/U0GS+xVpcHI8kJjFrQFiyFbO1NQFWBVAc3NFXHfSQvmNWYBYupRkMlreWWv66hdtPHTWq6rkypwhrNwJ7zUdiYuefUVcPlYDTYd3Hv9368FOoBTWMIosLZXyhU3pHFpLsZCuqVFh+GG7+JD94VmFTPGmUfIbbCGjaCIXwSzio833YG/2Cv5V4RH+qjuqXsbwX1kZxthdX6KC57TyY0TA+F2GJPuy7b0rDIpPH29e0uyNoh2BSYxaZBHNuoOJM/NIZbjQyoCQ+45KwH7LuIgaqkP5Vw0Ds5VYdMz593SzPUgf3T5qTnpMFX2Jh2m0FOBcnwsODtshOq7waI/tRdzU07YvgYoyeys+mUzK5TfboWie1PfBAwol006p336dEpdApY0X+m4W6DTa8otk8ToypXc+y5j7lY0TIUCGbCLygtjiOVsLm+ccCy7yZ6IAaFUWYHZOPaC8aOipIKxsz4/s5AJzI3hkcYoyTuO+oHoVLzKp4l0QUa+5VbTzMJ8E/g0tqeNXeE0Wk0cB4YJIAieo6dMvxD3x+ZEY73/4MALRNnwNg5hBIiGvvKDhsnAAcCKuOnLHOI3qwB0n9oSKMgD0h+trFoFtRilVHT6SOZVnkHy7eUoAzRTsmhQhvZgmDk9LG
    STRIPE_API_KEY: AgCkmpOWaf2Ew47r558Gg059eu8HGSX5yvw5TgfuOKUpjOJFt2YVFGCbmZzdRJ69yML5IUNSZuPhClrQ1lTi6xGGgSnAQ1pIn6/0Xua9Z510Y8LlnapIOUAK1YK0EQGL3cFUqGCOyFsl5SLNj4CYzdlzMfIhVK8OK0oG6iGjXANZLb1SuwHBjn8XolBv7zouP1shCWQSadkpbhUj+tRBNaxqpOaxsUp8vx109tvvzrz7KS2jr3AcT3QYXiAB70x4NGVLCE/3LOtrPTsfO4xGKrxyQZv3Ty0/C3G08OIxD4/MPPeLh6pgKpkTQ/KHS/8v5ivUkwqo80ueX2KbxPDruj7rXjpsgHJZfxeyvya0r7PdLOB7c3VhRKbz0bFhCGMZ0Se0t77Jtv3SfPOW0JrzoBnzpZ671by3R/wFZ64sbc8Nz/mzulyY1AuH2PRLpBDkR16Hp/loY6DIDMrCD3584HBBIV8hlWvzze1GqrGd2FhxagzXEr4iTacEUshoHAEp8UVCP5J1no+0L0euk2/teAA9jHsInQk1owZKL9iVOhgLMK/Ntj30OfDrFYJ73kOiERGatkhURO1uUeq+EEnyocYyXpiq9p36IGhwXSGllgVY3N24s0lIxKLZki6+g0QgJi/XKn2GoaceB4n6YQ1ZSSVnvEnfN+cW37Y1uQiucChs7BMI8mUFdWayLoElnbdG+eZicIFPH1Zj44R7E+4U3NBnYE6OBFv92GzqFLZxuah+18LbJBaLiJff
  template:
    metadata:
      name: ledger-secret
      namespace: payments
    type: Opaque
