---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgB5abq7kwUu/oB9e/2KtCQJZU/2IqG6kmvtDpILufAp9lsYftMm5umMal7EoTynXLN1zLA1ULnM4eXqkrCS6/NSQf9z1b7eTLrz3x0M7UBGNuYPc+1RnbBzmPkpPTfpnpL5S+MmUQrBrkyIbf1P4WmTQHj3kK0HDmlta9vYCKompK87bLbtSQwF83sook9Ag5lex1tfIgOZm574as+68XKhtcuYdxbulcxxfq9n5RRSXSuOwx3tnVTMN0xs2KCFtMflerbuhPISbDCwH5VXBUdk6cyxcNPDMQZZD1dKYuD3BvrwQ6mhPGTn02m4Za5hknq7+yI1/VRcNz13gSkBhuc556VRX0d0DUV17n28poPGPU/vLW41p2aIi5yawDugH5ymXHMaFVj3V6MBoXygSnIavXwTfWHoIbaJFO2tQJ0WdIk7gAMWsthqw0SWWHY36NK9ofFT/KkO1/2Zjfle/xMSRmZgBDqNEmlLNpYxjP1jLoHmK64tEGmqsEN8OgmSdUAelv/ES3XYD1+9OgaToHEvdThnDZBzN5uY8WSgceIx48MA/m16tpVZE4/AHz4X/h+SdhylCbM8N3bAfQBoK7XxA/iutLac0pF9o2IHGwAPkF9kRcumwF8ZU3kbmLBu9gimQmQH40f8FbaPlbgUdmezGA1dG3EKSHWu13gaxDB040A5PMJnx9/v/WGS4w1NzqI5kvCdrxIQgSP93A==
    STRIPE_API_KEY: AgAKRrGj+PLes8y/FnFpXeZdmFO2iladbCpMfhtB6t4VexO+HMwPu7kqbPnsiEnTPK6pd7wS1Dua1cSb1mewyBA4pVNwWXy405pWh3VYqxR/kJpNnCBZdyc7qT0tt0r4/Q1BrKQu1fV4582Ys9ze0EEjDorkhNh4LccC3Wqv9BkU9fatIBOVquMqt0jCg60jwU2fC7R2TkbjLzwPIFp8kGrQTh4vFmQk1hO32R47F+eZ1BAs710Qe05BrDhOEm0nh39BJ1/+OkAApzKE2rWwC86LLXJp4vAhYWB8BehxpTlmbwfqKruWd/zqWvnrxth2u5KWGWO+GswJSx2yVnVDM/dc5CdqoIN2ix7lcSAs8fjTnUokWU7VYJBNt9xf6mCBQG4FDgS0vnGuw6fKlX8fahg8lCIF0sxVSCGBR7KU9A3GtNqz78MOd5EVY3DK3qjJvt51gZ1lI6Xl2f/2pOwNRJCl5gQPdZrwPAtpRMfeA/rJTr2JtlkPXiqna8qilQqcW7nVOzHfyMJi35FW24VYECsk2o3ELhZ4T5P/0VQfMHz8MldfBkipx3DOI2U1gIRTOTU4kXvUxpxH5aNpDi+ibPyAmzI9RgAhM0R7fasMIZ5AhFInZeGqa3+6fKr/XyC6zkQkAqQQkqhbekueh4Bk4fjCNzyOyq/fQqxNEK8uXI3AB1Xv/pHutctq8UnSDlqmCAXc/43CnVQPj03qeQJRyEFjeOJ4NtgODckl+m4H9Q==
  template:
    metadata:
      name: ledger-secret
      namespace: payments
    type: Opaque
