---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: payments
spec:
  encryptedData:
    .dockerconfigjson: AgCGh13Ru+LIosbNWYlRTRs45JQBIa4ZvnFFBwzHe47L0RfwYcOwHTZUSknizDVgi0v0x34KEQiE2gD2qPm5vSaryEC6tDzf7jiYzhLPQmnCLRxvgVOO81syxaLChpqKjooYIyUnOcJkcViWa87wjQ3Ribm82wN1KJL5baYveMwrmAVQHVA3E+uiD1LjeYUm/MQNCLCb31Ml9Qg8S6r+YDxJYu8WKAkn3vVxSYeXBfqmxR10DfpQhUGO5CSZawjG4si1/3X311/Hf2RrZOGnSp9oyCxeMiBfkMsyF/VmHv9J3KGABTVW+e5hR1AG0rgHKfOyPj3/+4IxGmS1IWN5CjgcwMg4VRDsloOFWq/x6H7nNFuW/wXGaPS6bpcaMwZjGqmyeWD94H2QHuDvkEzaWrPpbqk++Af0drrEk/dB3Yrx0BdHrlWhtMr3tUiuUG3b7NELApTr6GqsnHGxAGUoSxTY53mILGDKJL9FDMvqkzjBI62DPdFej6c35kf67UqK+YlKpi0K7SYF9tOEWbm4RsxAqCRU1Mujz8clP3HG5EzozA4HQAIGJH8XHxDqTMKkTX43WfbnJ2OfFM0fSkjVEv6WCCfqlz469DdpXlwNzvGuLsl0XT+rcdwZgz0HGxhK15aACFzSW70pFzUGWYzV+p4CKK3XoQf7hyfuQqzE69kkft9mT2GwLHYsdziM4Oj1FqhU4HHzw+T0IHXc8GJQNaV2SMslfCqhSVA39He3mIjMRxw2PwNyA5DERw5q4yz0gxPDPigGm15TezOiE7FKeUatB4BvcEyHM9uFlGRPRY9ASiUKZP1T8WquwScHtx92jYG3OZPCG5uz3RnG5E9aVfLm/695FVOJMqhiHNuHrr6+NBEBRFNE+uxfoEmLYdg1i4sHr2DkT8V27xQGpVJkUXYnEnDOpSNpaM9U24zgDFuGETwZeDfInNBmZzoggQe7p2W9LtGoce2Bbxp34GOXEKWL3Q91jAcfxR4kK0WjiW1M1T0EqefZBWJ5yd6sabB9ARVTQm5pWwPc3UWt6RKUlXP+lJfseVlDOGcL8N2H2wiq
  template:
    metadata:
      name: ghcr-secret
      namespace: payments
    type: kubernetes.io/dockerconfigjson
